version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "ITMO-Stoma"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - pg-itmo-stoma

  pgadmin:
    container_name: pgadmin_container 
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@pgadmin.org"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - pg-itmo-stoma

networks:
  pg-itmo-stoma:
    driver: bridge
