version: "3.9"
networks:
  pg-itmo-stoma:
    driver: bridge
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "ITMO-Stoma"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgrespw"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - pg-itmo-stoma
